### ISSUE TITLE
Are you going to add bitcode support?

### ISSUE THREAD

**Issue by vandyshev** [voximplant/ios-sdk-swift-demo#1]

**Comment by YuliaGrigorieva** [comment]
Hello!

Voximplant iOS SDK is available with and without bitcode:
1. without bitcode via cocoapods
2. with bitcode via direct links to download, please find the information in this tutorial: https://voximplant.com/docs/references/iossdk/using-ios-sdk

Best regards,
Yulia Grigorieva

**Comment by vandyshev** [comment]
@YuliaGrigorieva Do you have any way to use bitcode version via cocoapods?

**Comment by YuliaGrigorieva** [comment]
Hello!

You can use Voximplant iOS SDK bitcode version with cocoapods.

After downloading and unpacking Voximplant iOS SDK bitcode version, add the following lines to your Podfile:

```
pod 'VoxImplantSDK', :path => '<path_to_downloaded_bitcode_version>'
pod 'VoxImplantWebRTC', :path => '<path_to_downloaded_bitcode_version>'
```

Best regards,
Yulia Grigorieva

**Comment by vandyshev** [comment]
But VoxImplantWebRTC size ~700mb. How can i use pod 'VoxImplantSDK' with ENABLE_BITCODE?

**Comment by YuliaGrigorieva** [comment]
Hello!

700mb is a bitcode build size that will be reduced a lot by Apple services while uploading to the TestFlight. That is how bitcode works, you can refer to the bitcode documentation for the details.

You can use pod 'VoxImplantSDK' with ENABLE_BITCODE by adding the aforementioned lines to your Podfile:

```
pod 'VoxImplantSDK', :path => '<path_to_downloaded_bitcode_version>'
pod 'VoxImplantWebRTC', :path => '<path_to_downloaded_bitcode_version>'
```
Best regards,
Yulia Grigorieva

**Comment by vandyshev** [comment]
It will be reduced a lot by Apple services but it's terrible while you debug app on device over wi-fi. All 700mb is copied to device. It takes a very long time

**Comment by YuliaGrigorieva** [comment]
Hello!

That's why usage of bitcode libraries is not recommended for debug/testing builds. 
You can disable bitcode for debug builds and enable it for release.

Best regards,
Yulia Grigorieva
