### ISSUE TITLE
Any chance to get Swift Package Manager support?

### ISSUE THREAD

**Issue by kek-dev** [voximplant/ios-sdk-swift-demo#10]
Can I use this lib without pods (e.g. binary target [xcframework] in my Swift Package)? Would be cool to see Swift Package Manager support if it is possible.

**Comment by akniev** [comment]
+1

**Comment by Hamoonist** [comment]
+1

**Comment by yoklmnprst** [comment]
Hello, @kek-dev . Swift Package Manager officially supported and available [here](https://github.com/voximplant/ios-sdk-releases).
