### ISSUE TITLE
404 issue

### ISSUE THREAD

**Issue by isurugajasinghe** [voximplant/ios-sdk-swift-demo#2]
![img_6689](https://user-images.githubusercontent.com/23732707/45419266-69293480-b6a4-11e8-8451-1aaca5cfd864.PNG)

how to fix this issue ?

**Comment by YuliaGrigorieva** [comment]
Hello!

Please ensure that you have created a JS scenario and application rule in the Voximplant control panel.
You can use our quickstart as a reference:
https://voximplant.com/docs/references/articles/quickstart/apps-scenarios-rules-and-users

Best regards,
Yulia Grigorieva
