### ISSUE TITLE
Implementation using with SwiftUI

### ISSUE THREAD

**Issue by bizmedia** [voximplant/ios-sdk-swift-demo#5]
Please provide sample app using new [SwiftUI](https://developer.apple.com/xcode/swiftui/)

**Comment by YuliaGrigorieva** [comment]
Hello @bizmedia ,

Thank you for reaching out to us!

We have plans to add a demo application based on SwiftUI.

However, if you have faced an issue with the integration of Voximplant iOS SDK with SwiftUI, please provide more details.

Best regards,
Yulia Grigorieva
