### ISSUE TITLE
ScreenSharing target crash issue

### ISSUE THREAD

**Issue by Qstove** [voximplant/ios-sdk-swift-demo#7]
UI calling from background thread.
This patch can solve the problem
[uiFromBackgroundThread.diff.zip](https://github.com/voximplant/ios-sdk-swift-demo/files/4737325/uiFromBackgroundThread.diff.zip)

**Backtrace:**
Main Thread Checker: UI API called on a background thread: -[UIViewController presentingViewController]
PID: 9551, TID: 247980, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   ScreenSharing                       0x0000000105f32f89 $s13ScreenSharing26IncomingCallViewControllerC11viewDidLoadyyFyycfU0_ys5Error_pSgcfU_ + 713
5   ScreenSharing                       0x0000000105f4cb73 $s13ScreenSharing17PermissionsHelperC013requestRecordC014includingVideo10completionySb_ys5Error_pSgctFZySbcfU_ySbcfU_ + 227
6   ScreenSharing                       0x0000000105f4cdba $sSbIegy_SbIeyBy_TR + 58
7   TCC                                 0x00007fff46bf1fe3 __TCCAccessRequest_block_invoke.126 + 337
8   TCC                                 0x00007fff46bf5dd1 __tccd_send_message_block_invoke + 231
9   libxpc.dylib                        0x00007fff51c4f8f7 _xpc_connection_reply_callout + 36
10  libxpc.dylib                        0x00007fff51c44b4f _xpc_connection_call_reply_async + 69
11  libdispatch.dylib                   0x00000001075bbef8 _dispatch_client_callout3 + 8
12  libdispatch.dylib                   0x00000001075d720a _dispatch_mach_msg_async_reply_invoke + 444
13  libdispatch.dylib                   0x00000001075ce336 _dispatch_kevent_worker_thread + 1589
14  libsystem_pthread.dylib             0x00007fff51c08a85 _pthread_wqthread + 362
15  libsystem_pthread.dylib             0x00007fff51c07b77 start_wqthread + 15
2020-06-05 19:09:34.089563+0300 ScreenSharing[9551:247980] [reports] Main Thread Checker: UI API called on a background thread: -[UIViewController presentingViewController]
PID: 9551, TID: 247980, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   ScreenSharing                       0x0000000105f32f89 $s13ScreenSharing26IncomingCallViewControllerC11viewDidLoadyyFyycfU0_ys5Error_pSgcfU_ + 713
5   ScreenSharing                       0x0000000105f4cb73 $s13ScreenSharing17PermissionsHelperC013requestRecordC014includingVideo10completionySb_ys5Error_pSgctFZySbcfU_ySbcfU_ + 227
6   ScreenSharing                       0x0000000105f4cdba $sSbIegy_SbIeyBy_TR + 58
7   TCC                                 0x00007fff46bf1fe3 __TCCAccessRequest_block_invoke.126 + 337
8   TCC                                 0x00007fff46bf5dd1 __tccd_send_message_block_invoke + 231
9   libxpc.dylib                        0x00007fff51c4f8f7 _xpc_connection_reply_callout + 36
10  libxpc.dylib                        0x00007fff51c44b4f _xpc_connection_call_reply_async + 69
11  libdispatch.dylib                   0x00000001075bbef8 _dispatch_client_callout3 + 8
12  libdispatch.dylib                   0x00000001075d720a _dispatch_mach_msg_async_reply_invoke + 444
13  libdispatch.dylib                   0x00000001075ce336 _dispatch_kevent_worker_thread + 1589
14  libsystem_pthread.dylib             0x00007fff51c08a85 _pthread_wqthread + 362
15  libsystem_pthread.dylib             0x00007fff51c07b77 start_wqthread + 15

Main Thread Checker: UI API called on a background thread: -[UIViewController dismissViewControllerAnimated:completion:]
PID: 9551, TID: 247980, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   ScreenSharing                       0x0000000105f330b8 $s13ScreenSharing26IncomingCallViewControllerC11viewDidLoadyyFyycfU0_ys5Error_pSgcfU_ + 1016
5   ScreenSharing                       0x0000000105f4cb73 $s13ScreenSharing17PermissionsHelperC013requestRecordC014includingVideo10completionySb_ys5Error_pSgctFZySbcfU_ySbcfU_ + 227
6   ScreenSharing                       0x0000000105f4cdba $sSbIegy_SbIeyBy_TR + 58
7   TCC                                 0x00007fff46bf1fe3 __TCCAccessRequest_block_invoke.126 + 337
8   TCC                                 0x00007fff46bf5dd1 __tccd_send_message_block_invoke + 231
9   libxpc.dylib                        0x00007fff51c4f8f7 _xpc_connection_reply_callout + 36
10  libxpc.dylib                        0x00007fff51c44b4f _xpc_connection_call_reply_async + 69
11  libdispatch.dylib                   0x00000001075bbef8 _dispatch_client_callout3 + 8
12  libdispatch.dylib                   0x00000001075d720a _dispatch_mach_msg_async_reply_invoke + 444
13  libdispatch.dylib                   0x00000001075ce336 _dispatch_kevent_worker_thread + 1589
14  libsystem_pthread.dylib             0x00007fff51c08a85 _pthread_wqthread + 362
15  libsystem_pthread.dylib             0x00007fff51c07b77 start_wqthread + 15
2020-06-05 19:09:34.389622+0300 ScreenSharing[9551:247980] [reports] Main Thread Checker: UI API called on a background thread: -[UIViewController dismissViewControllerAnimated:completion:]
PID: 9551, TID: 247980, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   ScreenSharing                       0x0000000105f330b8 $s13ScreenSharing26IncomingCallViewControllerC11viewDidLoadyyFyycfU0_ys5Error_pSgcfU_ + 1016
5   ScreenSharing                       0x0000000105f4cb73 $s13ScreenSharing17PermissionsHelperC013requestRecordC014includingVideo10completionySb_ys5Error_pSgctFZySbcfU_ySbcfU_ + 227
6   ScreenSharing                       0x0000000105f4cdba $sSbIegy_SbIeyBy_TR + 58
7   TCC                                 0x00007fff46bf1fe3 __TCCAccessRequest_block_invoke.126 + 337
8   TCC                                 0x00007fff46bf5dd1 __tccd_send_message_block_invoke + 231
9   libxpc.dylib                        0x00007fff51c4f8f7 _xpc_connection_reply_callout + 36
10  libxpc.dylib                        0x00007fff51c44b4f _xpc_connection_call_reply_async + 69
11  libdispatch.dylib                   0x00000001075bbef8 _dispatch_client_callout3 + 8
12  libdispatch.dylib                   0x00000001075d720a _dispatch_mach_msg_async_reply_invoke + 444
13  libdispatch.dylib                   0x00000001075ce336 _dispatch_kevent_worker_thread + 1589
14  libsystem_pthread.dylib             0x00007fff51c08a85 _pthread_wqthread + 362
15  libsystem_pthread.dylib             0x00007fff51c07b77 start_wqthread + 15
2020-06-05 19:09:34.446873+0300 ScreenSharing[9551:247980] [Assert] Cannot be called with asCopy = NO on non-main thread.
2020-06-05 19:09:34.447150+0300 ScreenSharing[9551:247980] [Assert] Cannot be called with asCopy = NO on non-main thread.
2020-06-05 19:09:34.447560+0300 ScreenSharing[9551:247980] [Assert] Cannot be called with asCopy = NO on non-main thread.
2020-06-05 19:09:34.447884+0300 ScreenSharing[9551:247980] [Assert] Cannot be called with asCopy = NO on non-main thread.
2020-06-05 19:09:34.448140+0300 ScreenSharing[9551:247980] [Assert] Cannot be called with asCopy = NO on non-main thread.
2020-06-05 19:09:34.448355+0300 ScreenSharing[9551:247980] [Assert] Cannot be called with asCopy = NO on non-main thread.
2020-06-05 19:09:34.448723+0300 ScreenSharing[9551:247980] *** Assertion failure in -[FBSSerialQueue assertOnQueue], /Library/Caches/com.apple.xbs/Sources/FrontBoardServices_Sim/FrontBoard-626.8/FrontBoardServices/FBSSerialQueue.m:98
2020-06-05 19:09:34.462710+0300 ScreenSharing[9551:247980] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'threading violation: expected the main thread'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3cf0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ba89b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e3cc88 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff258b8bd2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   FrontBoardServices                  0x00007fff36cf7d36 -[FBSSerialQueue assertOnQueue] + 236
	5   FrontBoardServices                  0x00007fff36cab2e5 -[FBSSceneImpl updateClientSettings:withTransitionContext:] + 70
	6   FrontBoardServices                  0x00007fff36cab52f -[FBSSceneImpl updateClientSettingsWithTransitionBlock:] + 153
	7   FrontBoardServices                  0x00007fff36cab455 -[FBSSceneImpl updateClientSettingsWithBlock:] + 110
	8   UIKitCore                           0x00007fff487b41b2 -[FBSScene(UIApp) updateUIClientSettingsWithBlock:] + 160
	9   UIKitCore                           0x00007fff4839d522 -[_UISystemAppearanceManager updateScreenEdgesDeferringSystemGestures] + 374
	10  UIKitCore                           0x00007fff48600672 __70-[UIViewController setNeedsUpdateOfScreenEdgesDeferringSystemGestures]_block_invoke_2 + 118
	11  UIKitCore                           0x00007fff485dec48 -[UIViewController _updateSystemAppearanceWithRecursionBlock:action:] + 295
	12  UIKitCore                           0x00007fff485deb72 -[UIViewController _updateSystemAppearanceWithRecursionBlock:action:] + 81
	13  UIKitCore                           0x00007fff486002b9 -[UIViewController _setPresentedStatusBarViewController:] + 220
	14  UIKitCore                           0x00007fff485f61f5 -[UIViewController _dismissViewControllerWithAnimationController:interactionController:completion:] + 675
	15  UIKitCore                           0x00007fff485f5d5a -[UIViewController _dismissViewControllerWithTransition:from:completion:] + 662
	16  UIKitCore                           0x00007fff485f54fb -[UIViewController dismissViewControllerWithTransition:completion:] + 1256
	17  UIKitCore                           0x00007fff485f52a2 -[UIViewController dismissViewControllerWithTransition:completion:] + 655
	18  UIKitCore                           0x00007fff485f4f37 -[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 511
	19  UIKitCore                           0x00007fff485f7811 -[UIViewController dismissViewControllerAnimated:completion:] + 135
	20  ScreenSharing                       0x0000000105f330b8 $s13ScreenSharing26IncomingCallViewControllerC11viewDidLoadyyFyycfU0_ys5Error_pSgcfU_ + 1016
	21  ScreenSharing                       0x0000000105f4cb73 $s13ScreenSharing17PermissionsHelperC013requestRecordC014includingVideo10completionySb_ys5Error_pSgctFZySbcfU_ySbcfU_ + 227
	22  ScreenSharing                       0x0000000105f4cdba $sSbIegy_SbIeyBy_TR + 58
	23  TCC                                 0x00007fff46bf1fe3 __TCCAccessRequest_block_invoke.126 + 337
	24  TCC                                 0x00007fff46bf5dd1 __tccd_send_message_block_invoke + 231
	25  libxpc.dylib                        0x00007fff51c4f8f7 _xpc_connection_reply_callout + 36
	26  libxpc.dylib                        0x00007fff51c44b4f _xpc_connection_call_reply_async + 69
	27  libdispatch.dylib                   0x00000001075bbef8 _dispatch_client_callout3 + 8
	28  libdispatch.dylib                   0x00000001075d720a _dispatch_mach_msg_async_reply_invoke + 444
	29  libdispatch.dylib                   0x00000001075ce336 _dispatch_kevent_worker_thread + 1589
	30  libsystem_pthread.dylib             0x00007fff51c08a85 _pthread_wqthread + 362
	31  libsystem_pthread.dylib             0x00007fff51c07b77 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
/Users/a17674005/Library/Developer/Xcode/DerivedData/Swift-eidfaosvnqznblgtsappcsmuhhzs/Build/Products/Debug-iphonesimulator/ScreenSharing.app/ScreenSharing: Cannot load Swift type information; AST validation error in "ScreenSharing": The module file format is too old to be used by this version of the debugger.
(Recorded stack frame)

**Comment by VladimirBrejcha** [comment]
Thank you, fixed!
