### ISSUE TITLE
Receive headers in didConnectWithHeaders

### ISSUE THREAD

**Issue by abdallahEid** [voximplant/ios-sdk-swift-demo#9]
Hello, 
I need to receive headers in didConnectWithHeaders func from VICallDelegate to be able to use image for example from the headers in  the app but headers dictionary is always empty.

Also I can receive headers in didReceiveIncomingCall func from VIClientCallManagerDelegate

Any help in this?
Thanks

**Comment by YuliaGrigorieva** [comment]
Hello @abdallahEid !

If a call is outgoing, you will receive the headers in [ [VICallDelegate call:didConnectWithHeaders: ]](https://voximplant.com/docs/references/iossdk/call/vicalldelegate#calldidconnectwithheaders) method that are set on the remote peer in [ [VICall answerWithSettings:] ](https://voximplant.com/docs/references/iossdk/call/vicall#answerwithsettings) method.
VoxEngine reference: https://voximplant.com/docs/references/voxengine/call#answer

If a call is incoming, you will receive the headers in [ [VIClientCallManagerDelegate client:didReceiveIncomingCall:withIncomingVideo:headers:] ](https://voximplant.com/docs/references/iossdk/client/viclientcallmanagerdelegate#clientdidreceiveincomingcallwithincomingvideoheaders) that are set on the remote peer in [ [VIClient call:settings:] ](https://voximplant.com/docs/references/iossdk/client/viclient#callsettings) method.

Best regards,
Yulia Grigorieva

**Comment by abdallahEid** [comment]
Hello @YuliaGrigorieva !
thanks for your response, If I need to receive the headers when it's from background mode or from the notification, this  [VIClientCallManagerDelegate client:didReceiveIncomingCall:withIncomingVideo:headers:] is not working so what can I do to receive headers from the notification or from background mode?

**Comment by YuliaGrigorieva** [comment]
Hello @abdallahEid !

I have checked that the headers set in [VIClient call:settings:] are received in [VIClientCallManagerDelegate client:didReceiveIncomingCall:withIncomingVideo:headers:] after the push is received.

Can you please check that the your headers meet the requirements, i.e. start with 'X-'?
If everything looks ok, please provide your VoxEngine scenario, so I will check it.

Best regards,
Yulia Grigorieva

**Comment by abdallahEid** [comment]
Thanks for your help
